# Simple workflow for deploying static content to GitHub Pages
name: Run File Checker

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: ubuntu-latest
    env:
      ARCHE_USER: pandorfer
      ARCHE_PASSWORD: ${{secrets.ARCHE_PASSWORD}}
      ARCHE: https://arche-dev.acdh-dev.oeaw.ac.at/api
      TOPCOLID: https://id.acdh.oeaw.ac.at/priscian-glosses
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download binary data
        run: ./fetch_data.sh
      - name: check files
        run: ./arche__filechecker.sh
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: "fc_out"
